# Generated by Django 2.1.1 on 2018-11-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('high', models.DecimalField(decimal_places=7, max_digits=15, null=True)),
                ('low', models.DecimalField(decimal_places=7, max_digits=15, null=True)),
                ('open', models.DecimalField(decimal_places=7, max_digits=15, null=True)),
                ('close', models.DecimalField(decimal_places=7, max_digits=15, null=True)),
                ('volume', models.DecimalField(decimal_places=7, max_digits=15, null=True)),
                ('adj_close', models.DecimalField(decimal_places=7, max_digits=15, null=True)),
            ],
        ),
    ]
