# Generated by Django 2.1.1 on 2018-11-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
