# Generated by Django 2.1.1 on 2018-11-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0002_auto_20181105_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
