# Generated by Django 2.1.1 on 2018-11-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0003_stockinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
