# Generated by Django 2.1.1 on 2018-11-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_trade', '0002_auto_20181109_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='share_amount',
            field=models.IntegerField(null=True),
        ),
    ]
