# Generated by Django 2.1.1 on 2018-11-10 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_info', '0002_auto_20181105_0328'),
        ('stock_trade', '0003_auto_20181109_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='stock_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_info.StockInfo'),
        ),
    ]
