# Generated by Django 2.1.1 on 2018-11-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_trade', '0005_auto_20181110_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='stock_info',
            field=models.ManyToManyField(blank=True, to='stock_info.StockInfo'),
        ),
    ]
