# Generated by Django 2.1.1 on 2018-11-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_trade', '0013_auto_20181110_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='share_amount',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
