# Generated by Django 2.1.1 on 2018-11-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_trade', '0014_auto_20181112_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='share_amount',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
        ),
    ]
