# Generated by Django 2.1.1 on 2018-11-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_auto_20181103_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
