# Generated by Django 2.1.1 on 2018-11-04 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_userprofileinfo_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
