# Generated by Django 2.1.1 on 2018-11-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0004_auto_20181104_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
