name: Widget Dispatch
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Testing Fetch
        run: |
          echo "The Enviroment Value is -:${{env.ENV}}"   
